baseURL = "https://www.nathankamgang.com/"
languageCode = "en-us"
title = "Nathan Kamgang"
theme = "ananke"

relativeURLs = true
canonifyURLs = false

# Enable LaTeX/Math rendering
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      unsafe = true
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchored = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

[caches]
  [caches.images]
    dir = ":cacheDir/images"

# Multi-language support
[languages]
  [languages.en]
    title = "Nathan Kamgang"
    weight = 1
    contentDir = "content/posts/en"
    languageCode = "en-us"
    languageName = "English"
    
  [languages.fr]
    title = "Nathan Kamgang"
    weight = 2
    contentDir = "content/fr"
    languageCode = "fr"
    languageName = "Français"

[params]
  author = "Nathan Kamgang"
  description = "Welcome to Nathan Kamgang's website"
  text_color = ""
  favicon = ""
  site_logo = ""
  background_color_class = "bg-black"
  recent_posts_number = 3
  # Enable math rendering
  math = true

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/GoHugoIO"

